### ISSUE TITLE
Make tests more stable

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#143]
Today a couple of builds failed on Travis while simply re-running the tests made them pass. For example:
https://travis-ci.org/c2corg/v6_api/builds/106766001

    FAIL: test_put_success_figures_and_lang_only (c2corg_api.tests.views.test_waypoint.TestWaypointRest)

    ----------------------------------------------------------------------

    Traceback (most recent call last):

      File "/home/travis/build/c2corg/v6_api/c2corg_api/tests/views/test_waypoint.py", line 402, in test_put_success_figures_and_lang_only

        (body, waypoint) = self.put_success_all(body_put, self.waypoint)

      File "/home/travis/build/c2corg/v6_api/c2corg_api/tests/views/__init__.py", line 513, in put_success_all

        self.assertEqual(meta_data_en.comment, 'Update')

    nose.proxy.AssertionError: 'creation' != 'Update'

    - creation

    + Update

I think this is because some tests are expecting that certain lists have a specific order, which is not guaranteed.

**Comment by tsauerwein** [comment]
Should be resolved with https://github.com/c2corg/v6_api/commit/952cbe0a40ca3c1f42d424f1a391adf0f8bb71f2.
