### ISSUE TITLE
ElasticSearch crash when filtering on bbox

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#284]
I have just updated the API demo instance (reimported the v5 data + updated the code).
There's 1 test failure:
```
ERROR: test_get_collection_search_bbox (c2corg_api.tests.views.test_waypoint.TestWaypointRest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/tests/views/test_waypoint.py", line 92, in test_get_collection_search_bbox
    {'bbox': '659000,5694000,660000,5695000'}),
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/tests/views/__init__.py", line 141, in get_collection_search
    response = self.app.get(prefix, headers=headers, status=200)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/webtest/app.py", line 323, in get
    expect_errors=expect_errors)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/webtest/app.py", line 606, in do_request
    res = req.get_response(app, catch_exc_info=True)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/webob/request.py", line 1295, in send
    application, catch_exc_info=True)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/webob/request.py", line 1263, in call_application
    app_iter = application(self.environ, start_response)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/webtest/lint.py", line 198, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 223, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 198, in invoke_subrequest
    response = handle_request(request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/__init__.py", line 46, in tween
    return handler(request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 48, in excview_tween
    request_iface=request_iface.combined
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 286, in _authdebug_view
    return view(context, request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 145, in handle_request
    view_name
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 541, in _call_view
    response = view_callable(context, request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 602, in __call__
    return view(context, request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 328, in attr_view
    return view(context, request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 304, in predicate_wrapper
    return view(context, request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 286, in _authdebug_view
    return view(context, request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 353, in rendered_view
    result = view(context, request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 507, in _requestonly_view
    response = view(request)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/cornice/service.py", line 571, in wrapper
    response = view_()
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/views/waypoint.py", line 121, in collection_get
    adapt_schema=listing_schema_adaptor)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/views/document.py", line 62, in _collection_get
    self.request.GET, meta_params, doc_type, clazz)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/search/advanced_search.py", line 9, in get_load_documents
    document_ids, total = search(url_params, meta_params, doc_type)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/c2corg_api/search/advanced_search.py", line 36, in search
    response = query.execute()
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/elasticsearch_dsl/search.py", line 579, in execute
    **self._params
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/elasticsearch/client/__init__.py", line 548, in search
    doc_type, '_search'), params=params, body=body)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    self._raise_error(response.status, raw_data)
  File "/var/www/vhosts/c2corgv6-api/private/v6_api/.build/venv/lib/python3.4/site-packages/elasticsearch/connection/base.py", line 108, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
nose.proxy.RequestError: TransportError(400, 'search_phase_execution_exception', "lat/lon is not enabled (indexed) for field [geom], can't use indexed filter on it")
```
@tsauerwein perhaps I have forgotten some new step?

**Comment by tsauerwein** [comment]
Likely because of a wrong ElasticSearch version.

**Comment by asaunier** [comment]
Right, I had forgotten this issue.

**Comment by asaunier** [comment]
The tests pass since @mfournier has upgraded ElasticSearch on the dev server (thanks!).

On the other I still get a similar error:
> elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', "lat/lon is not enabled (indexed) for field [geom], can't use indexed filter on it")

when adding a ``bbox`` parameter to the waypoints list request:
http://c2corgv6-demo.gis.internal:6545/waypoints?bbox=659000,5694000,660000,5695000

even with the same bbox value as in the tests:
https://github.com/c2corg/v6_api/blob/master/c2corg_api/tests/views/test_waypoint.py#L87-L93

**Comment by tsauerwein** [comment]
Did you recreate and refill the index?

**Comment by asaunier** [comment]
Nope...
Thanks for reminding!

**Comment by asaunier** [comment]
Index recreating. The refill is not finished yet but at least the bbox request now returns results => closing.
