### ISSUE TITLE
Last API version breaks the UI tests

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#371]
The API tests pass but when running the UI tests with a recent API, the latter tests fail saying that

> ======================================================================
ERROR: test_pages (c2corg_ui.tests.views.test_waypoint.TestWaypointUi)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/Desktop/v6_ui/c2corg_ui/tests/views/test_waypoint.py", line 22, in test_pages
    self._test_pages()
  File "/home/alex/Desktop/v6_ui/c2corg_ui/tests/views/__init__.py", line 38, in _test_pages
    response = self.app.get(route, status=404)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/webtest/app.py", line 323, in get
    expect_errors=expect_errors)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/webtest/app.py", line 606, in do_request
    res = req.get_response(app, catch_exc_info=True)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/webob/request.py", line 1295, in send
    application, catch_exc_info=True)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/webob/request.py", line 1263, in call_application
    app_iter = application(self.environ, start_response)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/webtest/lint.py", line 198, in lint_app
    iterator = application(environ, start_response_wrapper)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/home/alex/Desktop/v6_ui/c2corg_ui/caching/cacheversion.py", line 43, in __call__
    return self.handler(request)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
    result = view(context, request)
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 123, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/alex/Desktop/v6_ui/c2corg_ui/views/waypoint.py", line 54, in detail
    return self._get_or_create_detail(id, lang, render_page)
  File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 79, in _get_or_create_detail
    self._get_cache_key)
  File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 115, in _get_or_create
    not_modified, api_cache_key, loaded_data = load_data(old_api_cache_key)
  File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 74, in load_data
    self._get_document(id, lang, old_api_cache_key)
  File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 184, in _get_document
    url, old_api_cache_key)
  File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 220, in _get_with_etag
    resp, document = self._call_api(url, headers)
  File "/home/alex/Desktop/v6_ui/c2corg_ui/views/document.py", line 157, in _call_api
    return resp, resp.json()
  File "/home/alex/Desktop/v6_ui/.build/venv/lib/python3.4/site-packages/requests/models.py", line 733, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
nose.proxy.ValueError: Expecting value: line 1 column 1 (char 0)
-------------------- >> begin captured logging << --------------------
c2corg_ui.views: DEBUG: ETag didn't match, returning response object
c2corg_ui.views: DEBUG: ETag didn't match, returning response object
c2corg_ui.views.document: DEBUG: API: GET http://c2corgv6-demo.gis.internal:6545/waypoints/9999999999?l=fr
requests.packages.urllib3.connectionpool: DEBUG: "GET /waypoints/9999999999?l=fr HTTP/1.1" 500 56242

**Comment by tsauerwein** [comment]
The API tests pass, so it must be an UI issue! :P

I am taking a look..

**Comment by tsauerwein** [comment]
It's because you have to re-create the database.

**Comment by asaunier** [comment]
Ok, but then why does Travis report the error?

**Comment by tsauerwein** [comment]
And something was wrong with https://github.com/c2corg/v6_api/pull/340, Arnaud is on it.

**Comment by tsauerwein** [comment]
And in the Travis logs you can also see what went wrong with the API: https://travis-ci.org/c2corg/v6_ui/jobs/153223509#L5096

**Comment by asaunier** [comment]
OK, I'm reimporting my dev DB, thanks.
Feel free to close this issue when the fixes are pushed.
