### ISSUE TITLE
Feed KeyError 'c'

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_api#437]
on `/personal-feed?pl=es&token=50199%2C2016-03-21T17%3A11%3A54.627402` (after scrolling for a while) i get this error 

`KeyError: 'c'`

is it suppose to happen? something unfinished with the articles?

**Comment by tsauerwein** [comment]
Do you have some details about the error message, e.g a bit more of the stacktrace?

**Comment by ginold** [comment]
```
Traceback (most recent call last):
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_debugtoolbar/panels/performance.py", line 57, in resource_timer_handler
    result = handler(request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 51, in excview_tween
    request_iface=request_iface.combined
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 354, in _authdebug_view
    return view(context, request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
    result = view(context, request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 354, in _authdebug_view
    return view(context, request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/agina/v6_api/.build/venv/lib/python3.4/site-packages/cornice/service.py", line 571, in wrapper
    response = view_()
  File "/home/agina/v6_api/c2corg_api/views/feed.py", line 82, in get
    return load_feed(changes, lang)
  File "/home/agina/v6_api/c2corg_api/views/feed.py", line 268, in load_feed
    documents = load_documents(documents_to_load, lang)
  File "/home/agina/v6_api/c2corg_api/views/feed.py", line 353, in load_documents
    document_config = document_configs[document_type]
KeyError: 'c'
```

**Comment by tsauerwein** [comment]
Thanks!

Articles are missing here: https://github.com/c2corg/v6_api/blob/336da63f24ff8d6d3ac5853ac6dec5fd9c8fb478/c2corg_api/views/document_schemas.py#L211

@dkocich, do you maybe want to take a look?
