### ISSUE TITLE
Migration of articles should not create empty geometry rows

### ISSUE THREAD

**Issue by tsauerwein** [c2corg/v6_api#456]
During the migration of the articles, entries are created in table `guidebook.documents_geometries` and `guidebook.documents_geometries_archives`.

Because articles do not have a geometry, no rows should be created.

**Comment by dkocich** [comment]
@tsauerwein 
I tried to run full migration again and at the end of the process I get an error. There are problems with keys...

It looks that the fix of non-geometry articles/books is not so good.

```
Importing documents_versions
Total: 1250295 rows
1 of 1250295
2002 of 1250295
...
12012 of 1250295
14014 of 1250295
Traceback (most recent call last):
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 447, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.IntegrityError: insert or update on table "documents_versions" violates foreign key constraint "documents_versions_document_geometry_archive_id_fkey"
DETAIL:  Key (document_geometry_archive_id)=(14478) is not present in table "documents_geometries_archives".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dkocich/projects/c2corg/v6_api/c2corg_api/scripts/migration/migrate.py", line 93, in <module>
    main()
  File "/home/dkocich/projects/c2corg/v6_api/c2corg_api/scripts/migration/migrate.py", line 84, in main
    MigrateVersions(connection_source, session, batch_size).migrate()
  File "/home/dkocich/projects/c2corg/v6_api/c2corg_api/scripts/migration/documents/versions.py", line 71, in migrate
    self.get_version)
  File "/home/dkocich/projects/c2corg/v6_api/c2corg_api/scripts/migration/documents/versions.py", line 150, in _migrate
    batch.add(get_entity(entity_in))
  File "/home/dkocich/projects/c2corg/v6_api/c2corg_api/scripts/migration/batch.py", line 52, in add
    self.flush_or_not()
  File "/home/dkocich/projects/c2corg/v6_api/c2corg_api/scripts/migration/batch.py", line 14, in flush_or_not
    self.flush()
  File "/home/dkocich/projects/c2corg/v6_api/c2corg_api/scripts/migration/batch.py", line 59, in flush
    self.session.bulk_insert_mappings(self.model, self.entities)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2292, in bulk_insert_mappings
    mapper, mappings, False, False, return_defaults, False)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2363, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 183, in reraise
    raise value
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2358, in _bulk_save_mappings
    mapper, mappings, transaction, isstates, return_defaults)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 67, in _bulk_insert
    bookkeeping=return_defaults)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value.with_traceback(tb)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context)
  File "/home/dkocich/projects/c2corg/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 447, in do_executemany
    cursor.executemany(statement, parameters)
**sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) insert or update on table "documents_versions" violates foreign key constraint "documents_versions_document_geometry_archive_id_fkey"
DETAIL:  Key (document_geometry_archive_id)=(14478) is not present in table "documents_geometries_archives".**
 [SQL: 'INSERT INTO guidebook.documents_versions (id, document_id, lang, document_archive_id, document_locales_archive_id, document_geometry_archive_id, history_metadata_id) VALUES (%(id)s, %(document_id)s, %(lang)s, %(document_archive_id)s, %(document_locales_archive_id)s, %(document_geometry_archive_id)s, %(history_metadata_id)s)'] [parameters: ({'document_archive_id': 14153, 'id': 14153, 'history_metadata_id': 14153, 'lang': 'fr', 'document_locales_archive_id': 14153, 'document_geometry_archive_id': 14153, 'document_id': 14154}, {'document_archive_id': 14154, 'id': 14154, 'history_metadata_id': 14154, 'lang': 'fr', 'document_locales_archive_id': 14154, 'document_geometry_archive_id': 14154, 'document_id': 14155}, {'document_archive_id': 14155, 'id': 14155, 'history_metadata_id': 14155, 'lang': 'fr', 'document_locales_archive_id': 14155, 'document_geometry_archive_id': 14155, 'document_id': 14156}, {'document_archive_id': 14156, 'id': 14156, 'history_metadata_id': 14156, 'lang': 'fr', 'document_locales_archive_id': 14156, 'document_geometry_archive_id': 14156, 'document_id': 14157}, {'document_archive_id': 14157, 'id': 14157, 'history_metadata_id': 14157, 'lang': 'fr', 'document_locales_archive_id': 14157, 'document_geometry_archive_id': 14157, 'document_id': 14158}, {'document_archive_id': 14158, 'id': 14158, 'history_metadata_id': 14158, 'lang': 'fr', 'document_locales_archive_id': 14158, 'document_geometry_archive_id': 14158, 'document_id': 14159}, {'document_archive_id': 14160, 'id': 14160, 'history_metadata_id': 14160, 'lang': 'fr', 'document_locales_archive_id': 14160, 'document_geometry_archive_id': 14160, 'document_id': 14161}, {'document_archive_id': 14161, 'id': 14161, 'history_metadata_id': 14161, 'lang': 'fr', 'document_locales_archive_id': 14161, 'document_geometry_archive_id': 14161, 'document_id': 14162}  ... displaying 10 of 1001 total bound parameter sets ...  {'document_archive_id': 15168, 'id': 15172, 'history_metadata_id': 15172, 'lang': 'fr', 'document_locales_archive_id': 15172, 'document_geometry_archive_id': 15168, 'document_id': 15169}, {'document_archive_id': 15169, 'id': 15173, 'history_metadata_id': 15173, 'lang': 'fr', 'document_locales_archive_id': 15173, 'document_geometry_archive_id': 15169, 'document_id': 15170})]

Process finished with exit code 1

```

**Comment by tsauerwein** [comment]
You've run the migration with your unmerged branch `books`?

**Comment by dkocich** [comment]
Yes - with unmerged books.
I believe that it was ok without errors before when I migrated only books+articles+waypoints to test only part of the books user interface...

**Comment by tsauerwein** [comment]
> I believe that it was ok without errors before when I migrated only books+articles+waypoints to test only part of the books user interface...

You tested probably without `MigrateVersions(...).migrate()` in `migrate.py`.

**Comment by tsauerwein** [comment]
Can you please test with this patch in your `books` branch?

```
diff --git a/c2corg_api/scripts/migration/documents/versions.py b/c2corg_api/scripts/migration/documents/versions.py
index 046f27a..356fd45 100644
--- a/c2corg_api/scripts/migration/documents/versions.py
+++ b/c2corg_api/scripts/migration/documents/versions.py
@@ -49,13 +49,20 @@ versions_query_count =\
 
 versions_query =\
     'select ' \
+    '   t.documents_versions_id, t.document_id, t.culture, ' \
+    '   t.document_archive_id, t.document_i18n_archive_id, ' \
+    '   t.history_metadata_id, ' \
+    '   (a.geom is not null) as has_geom ' \
+    'from (select ' \
     '   v.documents_versions_id, v.document_id, v.culture, ' \
     '   v.document_archive_id, v.document_i18n_archive_id, ' \
     '   v.history_metadata_id ' \
     'from app_documents_versions v ' \
     '   inner join (' + tables_union + \
     '   ) u on u.id = v.document_id and u.redirects_to is null ' \
-    'group by v.documents_versions_id;'
+    'group by v.documents_versions_id) t ' \
+    'inner join app_documents_archives a ' \
+    '  on a.document_archive_id = t.document_archive_id;'
 
 
 class MigrateVersions(MigrateBase):
@@ -128,7 +135,8 @@ class MigrateVersions(MigrateBase):
             lang=row.culture,
             document_archive_id=row.document_archive_id,
             document_locales_archive_id=row.document_i18n_archive_id,
-            document_geometry_archive_id=row.document_archive_id,
+            document_geometry_archive_id=row.document_archive_id
+            if row.has_geom else None,
             history_metadata_id=row.history_metadata_id
         )
```

**Comment by dkocich** [comment]
I think we can close this one @asaunier ...? It should be ok now and books with fix are merged.

**Comment by asaunier** [comment]
I have no clue, @tsauerwein is better placed to give you the green light to close the issue :)

**Comment by stef74** [comment]
@tsauerwein can we test/close ?

**Comment by tsauerwein** [comment]
Confirmed, no geometries are create for articles and books.
