### ISSUE TITLE
frequent login issues

### ISSUE THREAD

**Issue by mfournier** [c2corg/v6_api#592]
several users have been complaining recently about «Il y a un problème avec votre compte. Merci de contacter l'administrateur du site.»

At least some of them can be correlated with an `Unexpected error: Invalid salt` in the logs, when POSTing to `/users/login`.

```
Traceback (most recent call last):
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 22, in excview_tween
 response = handler(request)
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 109, in tm_tween
 reraise(*exc_info)
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid_tm/compat.py", line 15, in reraise
 raise value
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 88, in tm_tween
 response = handler(request)
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 158, in handle_request
 view_name
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 547, in _call_view
 response = view_callable(context, request)
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 182, in __call__
 return view(context, request)
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 393, in attr_view
 return view(context, request)
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
 return view(context, request)
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
 result = view(context, request)
 File "/var/www/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
 response = view(request)
 File "/var/www/.build/venv/lib/python3.4/site-packages/cornice/service.py", line 485, in wrapper
 response = view_()
 File "/var/www/c2corg_api/views/user.py", line 433, in post
 token = try_login(user, password, request) if user else None
 File "/var/www/c2corg_api/security/roles.py", line 68, in try_login
 if user.email_validated and user.validate_password(password):
 File "/var/www/c2corg_api/models/user.py", line 142, in validate_password
 return PasswordUtil.is_password_valid(plain_password, self._password)
 File "/var/www/c2corg_api/models/user.py", line 51, in is_password_valid
 return bcrypt.hashpw(plain, encrypted) == encrypted
 File "/var/www/.build/venv/lib/python3.4/site-packages/bcrypt/__init__.py", line 86, in hashpw
 raise ValueError("Invalid salt")
ValueError: Invalid salt
```

**Comment by tsauerwein** [comment]
> several users have been complaining recently about «Il y a un problème avec votre compte. Merci de contacter l'administrateur du site.»

Where these users finally being able to login? Or was it a temporary problem?

**Comment by mgerbaux** [comment]
Probably linked to this ticket : https://github.com/c2corg/v6_forum/issues/70
It is possible to log on the topoguide, but impossible to log on the forum if several users share the same computer.
