### ISSUE TITLE
Problems deleting image files from the images backend

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_api#630]
The merging and deleting tools use the ``delete_all_files_for_image`` function
https://github.com/c2corg/v6_api/blob/81acc5a87544da06ec5c6a086aa2297d5448f868/c2corg_api/views/image.py#L116-L142
to remove image files from the images backend.

Testing in my instance, I have realized that the documents were actually merged/dropped but that the image files were still available after proceeding.

Steps to reproduce:
* open an image document
* middle-click on the image to open the file in a new tab
* delete or merge the image document => success
* try to reload the image file in the second tab => still accessible

For instance http://sos.exo.io/c2corg_demov6_active/1484838792_63859547.jpg should have been deleted.

Is it an API or an images backend issue?

**Comment by tsauerwein** [comment]
> Is it an API or an images backend issue?

Which image backend are you using? Is this backend up-to-date (e.g. it includes https://github.com/c2corg/v6_images/pull/36)?

**Comment by asaunier** [comment]
I use
```
export image_backend_url = https://images.demov6.camptocamp.org
export image_url = https://sos.exo.io/c2corg_demov6_active/
```

No clue if it is up-to-date. It uses release ``v6_images:v6.0.4``. Should it be OK?

**Comment by tsauerwein** [comment]
Tag [v6.0.4](https://github.com/c2corg/v6_images/tree/v6.0.4) includes https://github.com/c2corg/v6_images/pull/36, so it should work. I tried to reproduce the problem following your steps, but it worked for me.

Did you see any errors in the API or image backend logs?

Also note that the merging or deletion operation does not fail, if one or all images cannot be deleted (it's already to late to rollback the database transaction at that point), but you should at least see an error in the logs.

**Comment by asaunier** [comment]
I don't know if it can be related but those days I have trouble uploading images because of an error with 
> requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

I notice the same error when deleting an image: the image document is removed but not the image file
```
...
2017-02-21 12:29:39,630 INFO  [sqlalchemy.engine.base.Engine][waitress] {'type': 'i', 'document_id': 842098}
2017-02-21 12:29:39,633 INFO  [sqlalchemy.engine.base.Engine][waitress] COMMIT
2017-02-21 12:29:39,654 INFO  [requests.packages.urllib3.connectionpool][waitress] Starting new HTTPS connection (1): images.demov6.camptocamp.org
2017-02-21 12:29:39,798 ERROR [c2corg_api.search.notify_sync][waitress] Scheduled operation failed
Traceback (most recent call last):
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 577, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 804, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 621, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alex/v6_api/c2corg_api/search/notify_sync.py", line 50, in run_when_successful
    operation()
  File "/home/alex/v6_api/c2corg_api/views/image.py", line 139, in send_delete_request
    'filenames': filenames})
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
2017-02-21 12:29:39,817 INFO  [c2corg_api.search.notify_sync][waitress] Notifying ElasticSearch syncer
```

**Comment by tsauerwein** [comment]
The SSL certificate for the demo server seems not to be valid. I am not using SSL for the connection to the demo image backend (e.g. I use `export image_backend_url = http://images.demov6.camptocamp.org`).

**Comment by asaunier** [comment]
I have tried to upload images on the demo server and get an error whenever saving the image docs. See https://github.com/c2corg/v6_api/issues/637
