### ISSUE TITLE
Protected then unprotected articles

### ISSUE THREAD

**Issue by desnoes** [c2corg/v6_api#692]
When an article is protected and then unprotected it is not possible to save a modification. If the category is modified (eg. add a new category) then the problem disappears.

**Comment by asaunier** [comment]
Here are the logs when trying to edit the title of a route formerly protected then unprotected:
```
2017-10-27 16:22:29,716 ERROR [c2corg_api.views][waitress] Unexpected error: No row was found for one()
Traceback (most recent call last):
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 109, in tm_tween
    reraise(*exc_info)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid_tm/__init__.py", line 88, in tm_tween
    response = handler(request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/config/views.py", line 182, in __call__
    return view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 354, in _authdebug_view
    return view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 302, in _secured_view
    return view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 442, in rendered_view
    result = view(context, request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/cornice/service.py", line 485, in wrapper
    response = view_()
  File "/home/alex/v6_api/c2corg_api/views/route.py", line 136, in put
    after_update=update_title_prefix)
  File "/home/alex/v6_api/c2corg_api/views/document.py", line 254, in _put
    before_update, after_update)
  File "/home/alex/v6_api/c2corg_api/views/document.py", line 346, in update_document
    update_types,  changed_langs)
  File "/home/alex/v6_api/c2corg_api/views/document.py", line 416, in update_version
    archive = DocumentRest._get_document_archive(document, update_types)
  File "/home/alex/v6_api/c2corg_api/views/document.py", line 454, in _get_document_archive
    one()
  File "/home/alex/v6_api/.build/venv/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2760, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```
